#!/bin/python3

import math
import os
import random
import re
import sys
nkq = input().split()

n = int(nkq[0])

k = int(nkq[1])

q = int(nkq[2])

a = list(map(int, input().rstrip().split()))

queries = []

for _ in range(q):
    queries_item = int(input())
    queries.append(queries_item)
l=list(a)
while k>0:
        
    r=l[-1]
    l.pop()
    l.insert(0,r)
    k=k-1
for i in queries:
    print( l[i])
