#!/bin/python3

import os
import sys
def getMoneySpent(keyboards, drives, b):
    list_data = []
    for data in drives:
        for k in keyboards:
            total = data + k
            if total <= b:
                list_data.append(total)
            else:
                list_data.append(-1)
                
    
    max_data = max(list_data)
    
    return max_data
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    bnm = input().split()

    b = int(bnm[0])

    n = int(bnm[1])

    m = int(bnm[2])

    keyboards = list(map(int, input().rstrip().split()))

    drives = list(map(int, input().rstrip().split()))



    moneySpent = getMoneySpent(keyboards, drives, b)

    fptr.write(str(moneySpent) + '\n')

    fptr.close()
